name: matchmaking-platform
services:
- name: api
  source_dir: /
  github:
    repo: finyacht/Matchmaking
    branch: main
  run_command: node simple-server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: "production"
  - key: PORT
    value: "3000"
